AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: silent-signal-backend

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11

Resources:
  SilentSignalApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  NoiseEventsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: NoiseEventsTable
      PrimaryKey:
        Name: userId
        Type: String

  RoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RoomsTable
      AttributeDefinitions:
        - AttributeName: roomId
          AttributeType: S
      KeySchema:
        - AttributeName: roomId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DetectNoiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.detect_noise.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref NoiseEventsTable
      Events:
        ApiNoisePost:
          Type: Api
          Properties:
            RestApiId: !Ref SilentSignalApi
            Path: /noise
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NoiseEventsTable

  GetReadingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.get_readings.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref NoiseEventsTable
      Events:
        ApiNoiseGet:
          Type: Api
          Properties:
            RestApiId: !Ref SilentSignalApi
            Path: /noise
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NoiseEventsTable

  CreateRoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.create_room.handler
      Environment:
        Variables:
          ROOMS_TABLE: !Ref RoomsTable
      Events:
        ApiCreateRoom:
          Type: Api
          Properties:
            RestApiId: !Ref SilentSignalApi
            Path: /rooms
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RoomsTable
        - Statement:
            Effect: Allow
            Action:
              - chime:CreateMeeting
            Resource: '*'

  JoinRoomFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers.join_room.handler
      Environment:
        Variables:
          ROOMS_TABLE: !Ref RoomsTable
      Events:
        ApiJoinRoom:
          Type: Api
          Properties:
            RestApiId: !Ref SilentSignalApi
            Path: /rooms/{roomId}/join
            Method: post
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref RoomsTable
        - Statement:
            Effect: Allow
            Action:
              - chime:CreateAttendee
            Resource: '*'

Outputs:
  NoiseApiUrl:
    Description: "Noise API endpoint"
    Value: !Sub "https://${SilentSignalApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/noise"
  BaseApiUrl:
    Description: "Base URL for all API calls (rooms, noise, etc.)"
    Value: !Sub "https://${SilentSignalApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
